colors:
  time: white
  label: blue
  info: cyan
  error: red
  warning: yellow
  success: green
separators:
  simple: '-'
  powerline: ''
arrows:
  simple: '->'
  powerline: '❯'

showtime: yes
timefmt: '%H:%M:%S'
